<a href="https://colab.research.google.com/github/Sakib-Hossaine/Machine_Learing_Lab/blob/main/Lab_Practise_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b = np.array([[1,2],
              [3,4],
              [5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a.shape, b.shape

((4,), (3, 2))

In [5]:
c = np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))*9

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [ ]:
np.arange(0,10, 3)

array([0, 3, 6, 9])

In [ ]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [ ]:
c.shape, c.ndim, c.dtype

((3, 4), 2, dtype('float64'))

Exercise 1 (quick)

- Make a 3×3 array of all 7s
- Make numbers 1..12 and reshape to (3,4)

In [ ]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
x = np.array([10,20,30,40,50])
x, x[0], x[-2]

(array([10, 20, 30, 40, 50]), 10, 40)

In [ ]:
# x[begin:end]

x [2:]

array([30, 40, 50])

In [ ]:
x = np.array([[1,2,3,55,56,57],
             [4,5,6,66,67,68],
             [7,8,9,99,96,97],
             [33,44,50,23,45,23]])
x

array([[ 1,  2,  3, 55, 56, 57],
       [ 4,  5,  6, 66, 67, 68],
       [ 7,  8,  9, 99, 96, 97],
       [33, 44, 50, 23, 45, 23]])

In [ ]:
# x[row[b:e] , col[b:e]]

x[1,1], x[1,2]

(5, 6)

In [ ]:
x[1 , 1:3]

array([5, 6])

In [ ]:
x[1:3 , 1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
v = np.array([0.2,1.5,-0.7,3.3,2.2])
v

array([ 0.2,  1.5, -0.7,  3.3,  2.2])

In [ ]:
mask = v>1.0
mask

array([False,  True, False,  True,  True])

In [ ]:
v[mask==False]

array([ 0.2, -0.7])

In [ ]:
v[v>1.0]

array([1.5, 3.3, 2.2])

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

In [ ]:
x + y

array([11, 22, 33])

In [ ]:
x * y

array([10, 40, 90])

In [ ]:
# X: shape (n_samples, n_features)
# Here: 4 samples, 3 features
X = np.random.randn(4, 3)

print("X:\n", X)
print("Shape:", X.shape)  # (4, 3)

 # Global sum: reduces everything to a single number
print("Global sum:", X.sum())

# axis=0: reduce over rows -> gives one value per column (per feature)
print("Sum per feature (axis=0):", X.sum(axis=0))

# axis=1: reduce over columns -> gives one value per row (per sample)
print("Sum per sample (axis=1):", X.sum(axis=1))

X:
 [[-0.28668906 -0.14805059  0.78000724]
 [-1.65607495 -1.48946815  1.26921162]
 [ 0.99536607 -1.64309714 -0.40318177]
 [-0.11504095  0.45525924  0.37853852]]
Shape: (4, 3)
Global sum: -1.8632199189122438
Sum per feature (axis=0): [-1.06243889 -2.82535664  2.02457561]
Sum per sample (axis=1): [ 0.34526759 -1.87633148 -1.05091284  0.71875681]


In [ ]:
#Mean, std, min, max (common in preprocessing)
# Feature-wise mean (1 value per feature)
mu = X.mean(axis=0)
print("Mean per feature:", mu)

# Feature-wise std (1 value per feature)
sigma = X.std(axis=0)
print("Std per feature:", sigma)

# Feature-wise min/max
print("Min per feature:", X.min(axis=0))
print("Max per feature:", X.max(axis=0))

Mean per feature: [-0.26560972 -0.70633916  0.5061439 ]
Std per feature: [0.9416168  0.88766597 0.61246016]
Min per feature: [-1.65607495 -1.64309714 -0.40318177]
Max per feature: [0.99536607 0.45525924 1.26921162]


In [ ]:
A = np.ones((3, 2))
B = np.zeros((3, 2))

# Concatenate along axis=1 => append columns (more features)
C_feat = np.concatenate([A, B], axis=1)
print("Feature concat (axis=1):\n", C_feat)
print("Shape:", C_feat.shape)  # (3, 4)

# Concatenate along axis=0 => append rows (more samples)
C_samp = np.concatenate([A, B], axis=0)
print("Sample concat (axis=0):\n", C_samp)
print("Shape:", C_samp.shape)  # (6, 2)

# vstack/hstack are convenience wrappers (mostly for 2D)
print("vstack shape:", np.vstack([A, B]).shape)
print("hstack shape:", np.hstack([A, B]).shape)

Feature concat (axis=1):
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
Shape: (3, 4)
Sample concat (axis=0):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Shape: (6, 2)
vstack shape: (6, 2)
hstack shape: (3, 4)


In [ ]:
# A, B, np.vstack([A, B])
np.concatenate([A,B], axis=1).sum(axis=0)

array([3., 3., 0., 0.])

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('weather.csv')
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [ ]:
df.head()

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016           38        23        52                 30.03   
1  1/2/2016           36        18        46                 30.02   
2  1/3/2016           40        21        47                 29.86   
3  1/4/2016           25         9        44                 30.05   
4  1/5/2016           20        -3        41                 30.57   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
0               10           8.0               0           5    NaN   
1               10           7.0               0           3    NaN   
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   
4               10           5.0               0           0    NaN   

   WindDirDegrees  
0             281  
1             275  
2             277  
3             345  
4             333

In [ ]:
df.tail()

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
26               10           7.0               T           3   Rain   
27               10           5.0               0           1    NaN   
28               10           8.0               0           4    NaN   
29               10           7.0               0           0    NaN   
30               10           5.0               0           0    NaN   

    WindDirDegrees  
26             311  
27             234  
28             298  
29             257  
30             241

In [ ]:
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

In [ ]:
df.Temperature, df['Temperature'],  df[['EST','Temperature']]

(0     38
 1     36
 2     40
 3     25
 4     20
 5     33
 6     39
 7     39
 8     44
 9     50
 10    33
 11    35
 12    26
 13    30
 14    43
 15    47
 16    36
 17    25
 18    22
 19    32
 20    31
 21    26
 22    26
 23    28
 24    34
 25    43
 26    41
 27    37
 28    36
 29    34
 30    46
 Name: Temperature, dtype: int64,
 0     38
 1     36
 2     40
 3     25
 4     20
 5     33
 6     39
 7     39
 8     44
 9     50
 10    33
 11    35
 12    26
 13    30
 14    43
 15    47
 16    36
 17    25
 18    22
 19    32
 20    31
 21    26
 22    26
 23    28
 24    34
 25    43
 26    41
 27    37
 28    36
 29    34
 30    46
 Name: Temperature, dtype: int64,
           EST  Temperature
 0    1/1/2016           38
 1    1/2/2016           36
 2    1/3/2016           40
 3    1/4/2016           25
 4    1/5/2016           20
 5    1/6/2016           33
 6    1/7/2016           39
 7    1/8/2016           39
 8    1/9/2016           44
 9   1/10/2016           50
 10 

In [ ]:
df.Temperature.max(), df.Temperature.min(), df.Temperature.mean()

(50, 20, 34.67741935483871)

In [ ]:
df.iloc[1:5, 2:]

DewPoint  Humidity  Sea Level PressureIn  VisibilityMiles  WindSpeedMPH  \
1        18        46                 30.02               10           7.0   
2        21        47                 29.86               10           8.0   
3         9        44                 30.05               10           9.0   
4        -3        41                 30.57               10           5.0   

  PrecipitationIn  CloudCover Events  WindDirDegrees  
1               0           3    NaN             275  
2               0           1    NaN             277  
3               0           3    NaN             345  
4               0           0    NaN             333

In [ ]:
df.Events.unique()

array([nan, 'Rain', 'Fog-Snow', 'Snow'], dtype=object)

In [ ]:
df['EST'][]

0      1/1/2016
1      1/2/2016
2      1/3/2016
3      1/4/2016
4      1/5/2016
5      1/6/2016
6      1/7/2016
7      1/8/2016
8      1/9/2016
9     1/10/2016
10    1/11/2016
11    1/12/2016
12    1/13/2016
13    1/14/2016
14    1/15/2016
15    1/16/2016
16    1/17/2016
17    1/18/2016
18    1/19/2016
19    1/20/2016
20    1/21/2016
21    1/22/2016
22    1/23/2016
23    1/24/2016
24    1/25/2016
25    1/26/2016
26    1/27/2016
27    1/28/2016
28    1/29/2016
29    1/30/2016
30    1/31/2016
Name: EST, dtype: object

In [ ]:
df['EST'][df['Events']=='Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [ ]:
df[['EST','Temperature','VisibilityMiles']][df['Events']=='Rain']

EST  Temperature  VisibilityMiles
8    1/9/2016           44                9
9   1/10/2016           50                4
15  1/16/2016           47                8
26  1/27/2016           41               10

In [ ]:
df[df['Events']=='Rain']

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
15  1/16/2016           47        37        70                 29.52   
26  1/27/2016           41        22        45                 30.03   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
8                 9           8.0               T           8   Rain   
9                 4           NaN             1.8           7   Rain   
15                8           7.0            0.24           7   Rain   
26               10           7.0               T           3   Rain   

    WindDirDegrees  
8               76  
9              109  
15             340  
26             311

In [ ]:
df.isnull().sum()

EST                      0
Temperature              0
DewPoint                 0
Humidity                 0
Sea Level PressureIn     0
VisibilityMiles          0
WindSpeedMPH             3
PrecipitationIn          0
CloudCover               0
Events                  22
WindDirDegrees           0
dtype: int64

In [ ]:
df['Sea Level PressureIn'].max()

30.57

In [ ]:
df.fillna(1, inplace=True) #, inplace=True

In [ ]:
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5         1   
1                10           7.0               0           3         1   
2                10           8.0               0           1         1   
3                10           9.0               0           3         1   
4                10           5.0               0           0         1   
5                10           4.0               0           0         1   
6                10           2.0               0           3         1   
7                10           4.0               0           8         1   
8                 9           8.0               T           8      Rain   
9                 4           1.0             1.8           7      Rain   
10               10           1.0               0           1         1   
11               10           6.0               T           4         1   
12               10          10.0               0           0         1   
13               10           5.0               T           7         1   
14                9           5.0               T           2         1   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1         1   
19               10           6.0               0           2         1   
20               10           6.0               0           1         1   
21                9           1.0            0.01      

In [ ]:
df.isnull().sum()

EST                     0
Temperature             0
DewPoint                0
Humidity                0
Sea Level PressureIn    0
VisibilityMiles         0
WindSpeedMPH            0
PrecipitationIn         0
CloudCover              0
Events                  0
WindDirDegrees          0
dtype: int64

In [ ]:
df.replace(1, np.NaN, inplace=True)

In [ ]:
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0              10.0           8.0               0         5.0       NaN   
1              10.0           7.0               0         3.0       NaN   
2              10.0           8.0               0         NaN       NaN   
3              10.0           9.0               0         3.0       NaN   
4              10.0           5.0               0         0.0       NaN   
5              10.0           4.0               0         0.0       NaN   
6              10.0           2.0               0         3.0       NaN   
7              10.0           4.0               0         8.0       NaN   
8               9.0           8.0               T         8.0      Rain   
9               4.0           NaN             1.8         7.0      Rain   
10             10.0           NaN               0         NaN       NaN   
11             10.0           6.0               T         4.0       NaN   
12             10.0          10.0               0         0.0       NaN   
13             10.0           5.0               T         7.0       NaN   
14              9.0           5.0               T         2.0       NaN   
15              8.0           7.0            0.24         7.0      Rain   
16              8.0           6.0            0.05         6.0  Fog-Snow   
17              9.0          12.0               T         2.0      Snow   
18             10.0          11.0               0         NaN       NaN   
19             10.0           6.0               0         2.0       NaN   
20             10.0           6.0               0         NaN       NaN   
21              9.0           NaN            0.01      

In [ ]:
df.interpolate()

/var/folders/s7/nhlmv2hx4vg32r27lhnh40t00000gn/T/ipykernel_68180/4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()


EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0              10.0      8.000000               0         5.0       NaN   
1              10.0      7.000000               0         3.0       NaN   
2              10.0      8.000000               0         3.0       NaN   
3              10.0      9.000000               0         3.0       NaN   
4              10.0      5.000000               0         0.0       NaN   
5              10.0      4.000000               0         0.0       NaN   
6              10.0      2.000000               0         3.0       NaN   
7              10.0      4.000000               0         8.0       NaN   
8               9.0      8.000000               T         8.0      Rain   
9               4.0      7.333333             1.8         7.0      Rain   
10             10.0      6.666667               0         5.5       NaN   
11             10.0      6.000000               T         4.0       NaN   
12             10.0     10.000000               0         0.0       NaN   
13             10.0      5.000000               T         7.0       NaN   
14              9.0      5.000000               T         2.0       NaN   
15              8.0      7.000000            0.24         7.0      Rain   
16              8.0      6.000000            0.05         6.0  Fog-Snow   
17              9.0     12.000000               T         2.0      Snow   
18             10.0     11.000000               0         2.0       NaN   
19             10.0      6.000000               0         2.0       NaN   
20             10.0      6.000000               0         2.5       NaN   
21              9.0     11.000000            0.01      

In [ ]:
import pandas as pd
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(weather_data)
# df = pd.read_csv("weather_data.csv")
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df[1:4]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow

In [ ]:
df.loc[1:4]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [ ]:
df.iloc[0:4]

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow

In [ ]:
df['day'][df['temperature'] == df['temperature'].max()]

1    1/2/2017
Name: day, dtype: object

In [ ]:
df['temperature'].max()

35

In [ ]:
df[df['temperature'] == df['temperature'].max()]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [ ]:
df.describe() #include='O'

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [ ]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.set_index('day', inplace=True)

In [ ]:
df.columns, df.index

(Index(['temperature', 'windspeed', 'event'], dtype='object'),
 Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='object', name='day'))

In [ ]:
df.loc["1/1/2017":"1/4/2017"]

temperature  windspeed  event
day                                    
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow

In [ ]:
df.reset_index(inplace=True)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
df = pd.read_csv("weather_data.csv")
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.columns = ['d','t','w','e']
df

d   t  w      e
0  1/1/2017  32  6   Rain
1  1/2/2017  35  7  Sunny
2  1/3/2017  28  2   Snow
3  1/4/2017  24  7   Snow
4  1/5/2017  32  4   Rain
5  1/6/2017  31  2  Sunny